version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        update-types: ["patch"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
